name: Integration Tests
on:
  workflow_dispatch:
  pull_request:
    branches-ignore: ['llvm-**']
  merge_group:
    branches: [main, 'dev-**']
    types: [checks_requested]
  push:
    branches: [main]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
permissions: read-all

jobs:

  runner-preparation:
    uses: ./.github/workflows/runner-preparation.yml

  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  integration-tests-cpu:
    needs: runner-preparation
    if: needs.runner-preparation.outputs.matrix-CPU != ''
    uses: ./.github/workflows/integration-tests-cpu.yml
    with:
      matrix: ${{ needs.runner-preparation.outputs.matrix-CPU }}

  integration-tests-macos:
    needs: runner-preparation
    if: needs.runner-preparation.outputs.matrix-MACOS != ''
    uses: ./.github/workflows/integration-tests-macos.yml
    with:
      matrix: ${{ needs.runner-preparation.outputs.matrix-MACOS }}

  integration-tests-tenstorrent:
    needs: runner-preparation
    if: needs.runner-preparation.outputs.matrix-TENSTORRENT != ''
    uses: ./.github/workflows/integration-tests-tenstorrent.yml
    with:
      matrix: ${{ needs.runner-preparation.outputs.matrix-TENSTORRENT }}
